import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Marquee from "@/components/Marquee";
import Footer from "@/components/Footer"
const notoSerifBengali = Noto_Serif_Bengali({

  subsets: ["latin", 'bengali'],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon:'/logo.webp'
  }
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      data-theme='light'
      lang="en"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
        <Marquee></Marquee>
        <main className="max-w-7xl mx-auto">
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
